apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
  labels:
    app: php-app
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: nginx
        image: thechetantalwar/php