apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling_update
  labels:
    app: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-demo
        image: thechetantalwar/php