apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  labels:
      app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-demo
        image: thechetantalwar/php
